apiVersion: apps/v1
kind: Deployment
metadata:
  name: redash-scheduler
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: redash-scheduler
  template:
    metadata:
      labels:
        app: redash-scheduler
    spec:
      containers:
      - name: redash-scheduled-worker
        image: "{{ .Values.redash.image.name }}:{{ .Values.redash.image.tag }}"
        args: ["scheduler"]
        envFrom:
        - configMapRef:
            name: redash-config
        env:
          - name: REDASH_LOG_LEVEL
            value: "{{ .Values.redash.log_level.scheduler }}"
        resources:
          limits:
            cpu: {{ .Values.redash.limits.cpu }}
            memory: {{ .Values.redash.limits.mem }}
          requests:
            cpu: {{ .Values.redash.requests.cpu }}
            memory: {{ .Values.redash.requests.mem }}