apiVersion: v2
name: redash
version: 0.0.1
appVersion: 10.1.0
type: application
description: Redash is designed to enable anyone, regardless of the level of technical sophistication, to harness the power of data big and small. SQL users leverage Redash to explore, query, visualize, and share data from any data sources. Their work in turn enables anybody in their organization to use the data. Every day, millions of users at thousands of organizations around the world use Redash to develop insights and make data-driven decisions.

dependencies:
- name: postgresql
  repository: file://charts/postgresql
  version: 0.0.1
  condition: postgresql.from_subchart

- name: redis
  repository: file://charts/redis
  version: 0.0.1
  condition: redis.from_subchart