apiVersion: apps/v1
kind: Deployment
metadata:
  name: redash-scheduled-worker
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: redash-scheduled-worker
  template:
    metadata:
      labels:
        app: redash-scheduled-worker
    spec:
      containers:
      - name: redash-scheduled-worker
        image: "{{ .Values.redash.image.name }}:{{ .Values.redash.image.tag }}"
        args: ["worker"]
        envFrom:
        - configMapRef:
            name: redash-config
        env:
          - name: REDASH_LOG_LEVEL
            value: "{{ .Values.redash.log_level.scheduled_worker }}"
          - name: WORKERS_COUNT
            value: "1"
          - name: QUEUES
            value: "scheduled_queries,schemas"
        resources:
          limits:
            cpu: {{ .Values.redash.limits.cpu }}
            memory: {{ .Values.redash.limits.mem }}
          requests:
            cpu: {{ .Values.redash.requests.cpu }}
            memory: {{ .Values.redash.requests.mem }}