apiVersion: v1
kind: PersistentVolume
metadata:
  name: redash-postgresql-pv
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - {{ .Values.postgresql.pv_access_modes }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/outline/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db-volume
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.postgresql.pv_access_modes }}
  resources:
    requests:
      storage: 25Gi