{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: {{ .Values.global.namespace }}
data:
  tls.key: {{ .Values.ingress.tls.key }}
  tls.crt: {{ .Values.ingress.tls.crt }}
type: kubernetes.io/tls
{{- end }}