apiVersion: v1
kind: Service
metadata:
  name: redash-server-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redash-server
spec:
  ports:
  - port: {{ .Values.redash.port }}
    name: redash
  type: {{ .Values.redash.service.type }}
  selector:
    app: redash-server